/**
 * This file is autogenerated by Scaffold-Toro.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "@/types/contract";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
