const fs = require("fs");
const json5 = require("json5");

function dumpContractDetailsToFrontendModule(contractDetails) {
  const { network, contractName, abi, address, owner } = contractDetails;
  const newContract = {
    [contractName]: {
      owner,
      address,
      abi,
      external: false,
    },
  };

  // read deployedContracts.jsonc to see the previously deployed contracts
  const deployedContracts = json5.parse(
    fs.readFileSync("../core/contracts/deployedContracts.jsonc", { encoding: "utf8" }),
  );

  // merged with new contract deployments
  const newContracts = { ...deployedContracts, ...{ [network]: { ...deployedContracts[network], ...newContract } } };

  // write to deployedContract.ts
  const content = `/**
 * This file is autogenerated by Scaffold-Toro.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "@/types/contract";

const deployedContracts = ${JSON.stringify(newContracts, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;
  fs.writeFileSync("../core/contracts/deployedContract.ts", content, { encoding: "utf8" });

  // write to deployedContracts.json
  const jsonContent = `/**
 * This file is autogenerated by Scaffold-Toro.
 * You should not edit it manually or your changes might be overwritten.
 */

${JSON.stringify(newContracts, null, 2)}
`;
  fs.writeFileSync("../core/contracts/deployedContracts.json", jsonContent, { encoding: "utf8" });
}

module.exports = {
  dumpContractDetailsToFrontendModule,
};
