const fs = require("fs");
const json5 = require("json5");

/**
 * @typedef {Object} ContractDetails
 * @property {'testnet'|'mainnet'} [network] - Defaults to 'testnet'
 * @property {Object} abi - Deployed contract ABI
 * @property {string} contractName - Contract name to deploy
 * @property {string} owner - Owner wallet address
 * @property {string} address - Deployed contract address
 */

/**
 * Compiles and deploys a Solidity contract.
 * @param {ContractDetails} contractDetails
 * @returns {void}
 */
function dumpContractDetailsToFrontendModule(contractDetails) {
  const { network = "testnet", contractName, abi, address, owner } = contractDetails;
  const newContract = {
    [contractName]: {
      owner,
      address,
      abi,
      external: false,
    },
  };
  const JSON_DUMP_FILE = "../core/contracts/deployedContracts.jsonc";
  const TYPESCRIPT_DUMP_FILE = "../core/contracts/deployedContract.ts";

  // read deployedContracts.jsonc to see the previously deployed contracts
  const deployedContracts = json5.parse(fs.readFileSync(JSON_DUMP_FILE, { encoding: "utf8" }));

  // merged with new contract deployments
  const newContracts = { ...deployedContracts, ...{ [network]: { ...deployedContracts[network], ...newContract } } };

  // write to deployedContract.ts
  const content = `/**
 * This file is autogenerated by Scaffold-Toro.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "@/types/contract";

const deployedContracts = ${JSON.stringify(newContracts, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(TYPESCRIPT_DUMP_FILE, content, { encoding: "utf8" });

  // write to deployedContracts.json
  const jsonContent = `/**
 * This file is autogenerated by Scaffold-Toro.
 * You should not edit it manually or your changes might be overwritten.
 */

${JSON.stringify(newContracts, null, 2)}
`;
  fs.writeFileSync(JSON_DUMP_FILE, jsonContent, { encoding: "utf8" });
}

module.exports = {
  dumpContractDetailsToFrontendModule,
};
